ContextPath = "sqlweb"
ListenPort  = 8381
#MaxQueryRows  = 1000
DSN = "root:root@tcp(127.0.0.1:3306)/information_schema?charset=utf8"
#DevMode = true
BasicAuth= ["user:user", "bingoo:bingoo"]
MultiTenants = true
#ImportDb = false
#DefaultDB = ""
