ContextPath = "sqlweb"
ListenPort  = 8381
#MaxQueryRows  = 1000
DSN = "betaapiadmin:DVvLoqt4ootvGuu@tcp(123.206.185.162:53306)/metrics_ump?charset=utf8"
#DevMode = true
BasicAuth= ["user:user", "bingoo:bingoo"]
MultiTenants = true
#ImportDb = false
#DefaultDB = ""
